### ISSUE TITLE
English language broken

### ISSUE THREAD

**Issue by Lumine01-io** [Texas124/ZZZ-Integrity-Autopatch-Release#2]
Is it just me? My english languange suddenly crashed after using this new url.. but other language seems fine

**Comment by Texas124** [comment]
shouldn't be the case for this fix, if the game crashes maybe [unity fix](https://rentry.org/zzz-manual-install#unityplayer-fix) will solve it.

**Comment by Lumine01-io** [comment]
![Uploading 20240814_235257.jpg…]()
![Uploading 20240814_235305.jpg…]()
 Any idea how to solve this, if not its okay.
