### ISSUE TITLE
Antivirus 

### ISSUE THREAD

**Issue by Roxas1009** [Texas124/ZZZ-Integrity-Autopatch-Release#3]
My PC detects it as a virus, is it normal or not? Before it wasn't detecting it as a virus

**Comment by Texas124** [comment]
it's normal for unverified program to detected as virus in antivirus software. try adding this program as an exception

**Comment by Roxas1009** [comment]
Oh, I legit got a little bit scared there because I thought the program got hacked or somehow like that, since it was a high alert

**Comment by Roxas1009** [comment]
Thanks for the help
