### ISSUE TITLE
When new 1.2 Autopatch? 

### ISSUE THREAD

**Issue by VoidFallDragon** [Texas124/ZZZ-Integrity-Autopatch-Release#4]
The new one Url.txt for 1.2 does not work and please make the new autopatch thank you. There must be some easier way Thanks

**Comment by Texas124** [comment]
press the `copy link` and copy the link from address bar to the `url.txt`. it's quite easy

**Comment by Texas124** [comment]
well not all ppl cant understand how to copy & paste i guess so there you go: 
[Download release here](https://github.com/Texas124/ZZZ-Integrity-Autopatch-Release/raw/main/ZZZ%20Integrity%20Auto%20Patcher.zip)
