### ISSUE TITLE
why does this files contains trojan??, because of this i cant play it anymore..

### ISSUE THREAD

**Issue by xenobem** [Texas124/ZZZ-Integrity-Autopatch-Release#5]
![image_2024-09-25_103600690](https://github.com/user-attachments/assets/9d27d0ca-c285-4a22-8ba2-f9211ebd0d4f)

**Comment by Texas124** [comment]
[check here](https://github.com/Texas124/ZZZ-Integrity-Autopatch-Release?tab=readme-ov-file#antivirus-bypass)
